apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS PARKING (
        id SERIAL PRIMARY KEY,
        direction VARCHAR(255),
        bikesCapacity INT,
        latitude FLOAT,
        longitude FLOAT
    );

    INSERT INTO PARKING (id, direction, bikesCapacity, latitude, longitude) VALUES
    (1, 'Calle A, 123', 30, 39.4700, -0.3760),
    (2, 'Avenida B, 45', 25, 39.4710, -0.3770),
    (3, 'Calle C, 678', 40, 39.4725, -0.3785),
    (4, 'Paseo D, 89', 35, 39.4695, -0.3745),
    (5, 'Calle E, 10', 20, 39.4680, -0.3790),
    (6, 'Avenida F, 111', 50, 39.4735, -0.3800),
    (7, 'Calle G, 56', 15, 39.4740, -0.3755),
    (8, 'Paseo H, 300', 28, 39.4755, -0.3730),
    (9, 'Calle I, 99', 32, 39.4705, -0.3725),
    (10, 'Avenida J, 150', 45, 39.4760, -0.3710);
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db
  labels:
    app: mysql-db
spec:
  serviceName: mysql-db
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: parking_db
            - name: MYSQL_USER
              value: parking
            - name: MYSQL_PASSWORD
              value: parking1234
            - name: MYSQL_ROOT_PASSWORD
              value: root1234
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-init-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:  
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-init-volume
          configMap:
            name: mysql-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  labels:
    app: mysql-db
spec:
  clusterIP: None # Headless service
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql-db