apiVersion: apps/v1
kind: Deployment
metadata:
  name: estaciones-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: estaciones-api
  template:
    metadata:
      labels:
        app: estaciones-api
    spec:
      containers:
        - name: estaciones-api
          image: isi3/estaciones-api:latest
          ports:
            - containerPort: 9091
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://$(MYSQL_HOST):3306/$(MYSQL_DB)
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: estaciones-api-config
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: estaciones-api-secret
                  key: mysql-password
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@$(MONGO_HOST):27017/$(MONGO_DB)
            - name: MONGO_USER
              valueFrom:
                configMapKeyRef:
                  name: estaciones-api-config
                  key: MONGO_USER
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: estaciones-api-secret
                  key: mongodb-root-password
            - name: AUTH_API_URL
              valueFrom:
                configMapKeyRef:
                  name: estaciones-api-config
                  key: AUTH_API_URL